<?php 
return[
	'ID_SITIO' => '432',
	'URL_API' => 'https://apirest.fidelitytools.net/api/',
	'URL_REST' => 'https://rest.fidelitytools.net/Fidelitytools/',
	'URL_WS' => 'https://ws.fidelitytools.net/v2/api',
	'FIDELITY_KEY' => '265c092ff1813072ffeb07ec2ab84e4d',
	'WS_KEY' => '5d52c64c5cb8340f980bdaab',
	'PAGE_CACHE' => '',
	'ID_ANALYTIICS' => '123',
	'IDIOMA_DEFAULT' => 'es',
	'MULTIDIOMAS' => '1',
	'NOMBRE_SITIO' => 'El Centro Del Peinador',
	'ID_DESCUENTOS' => '0',
	'ID_ECOMMERCE' => '9322',
	'ID_ECOMMERCE_ENCODE' => 'OTMyMg',
	'JS_MAP' => '',
	'JS_SCROLLING' => '',
	'JS_SCROLLING_LIMIT' => '',
	'JS_SCROLLING_LOADING' => '1',
	'JS_SHOPPING_CART' => '',
	'META_DESCRIPTION' => '',
	'META_KEYWORDS' => '',
	'USUARIO_TWITTER' => '@',
	'IS_CACHE' => '',
	'CACHE' => '1',
	'CACHE_CATEGORIA' => '7200',
	'CACHE_CONTENIDO' => '5',
	'CACHE_PERSONA' => '3600',
	'CACHE_PRODUCTO' => '600',
	'CACHE_ARCHIVO' => '7200',
	'CACHE_ETIQUETA' => '7200',
];